import type { Metadata } from "next";
import "./globals.css";
// import localFont from 'next/font/local'
// const myFont = localFont({ src: '' })
import Header from '../components/header/Header'
import Footer from '../components/footer/Footer'

export const metadata: Metadata = {
  title: "Masa Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className="{`${myFont.className}`}">
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
