import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import Header from '../components/header/Header'
import Footer from '../components/footer/Footer'
import Link from "next/link";

export const metadata: Metadata = {
  title: "Masa",
  description: "Generated by Masa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <head>
        <link rel="icon" href="/navbar/logo_masa.svg" />
      </head>
      <body style={{ fontFamily: 'CustomFontName, sans-serif' }}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
        <div style={{
          position: "fixed",
          left: "2rem",
          bottom: "5rem",
          zIndex: 1000, // للتأكد من أنها تظهر فوق جميع العناصر الأخرى
        }}>
          <Link  href="https://wa.me/+9660510350361" target="_blank" className="block lg:hidden">
            <Image src="/footer/whatsapp.png" alt="..." width={60} height={20} />
          </Link>
          <Link  href="https://web.whatsapp.com/send?phone=+966 0510350361" target="_blank" className="hidden lg:block">
            <Image src="/footer/whatsapp.png" alt="..." width={60} height={20} />
          </Link>
        </div>
      </body>
    </html>
  );
}
